---
title: "The Balance of Hedonism and Stoicism for Personal Well-Being"
format: html
---

#### Things to do in: 
- what even is *personal wellbeing*?

*When we are no longer able to change a situation, we are challenged to change ourselves* - Viktor Frankl

*I exist only as a whole; my only claim is to be natural, and the pleasure I feel in an action, I take it as a sign that I ought to do it* - Andre Gilde

Are philosophies practicall or useful, or only guiding principles to give external perspectives as we go about our day to day life. 

Is hedionism really enjoyable in the long-term, or is it a short term juxapositio

Stoicism and hedonism are armchair phiosophies that do not represent a meaningful or fulfilling life. Authors like Ryan Holiday use quotes from stoics as "guiding principles", but do not actually believe as a stoic. 

What I would say is that understsanding different philosophical points to draw upon as "guuiding principles"
**Perspectives in life that I have that are opposed to stoicism: **
- I have personal desires that I would prefer to work towards that other things that I know would be **better** for the *greater good*.
- I care about external things, i.e., I strive towards externally-important professional career, I care about my relationships with others. 

**Perspectives of stoic philosophy that I find useful:**
- The idea that every obstacle that you face is an oppurtunity to practice some form of virtue. 

**Perspectives in life that I have that are opposed to hedonism:**
- I get no long-term fulfillment from most hedonistic pleasures that I would *do* day-to-day. 
- When viewing the person that I want to become, often times, hedonistic behaviour would play no part in getting there. 

**Perspectives of hedonistic philosophy that I find useful:**
- building new routines and habits are hard. Finding immediate reward is beneficsal for me to hold these new systems. 

**Ultimate thought:** Do not get bogged down into lively strictly towards any one philosophical ideaology; in my mind, they are more theoretical than practically useful. 
