---
title: "The Art of Focus - questions by Dan Koe Chapter 1"
format: html
---

### Questions from the **1) Introductions** chapter that I want to think about: 

#### What is the state of modern society? 
- insecure  
    - why? 
    - what societal systems excabrate this 
- comparison to others 
    - the age of societal media
- quick fix
    - what are some of the examples of how society looks for quick fixes to complex problems
    - how does the quest for instant gratification impact long-term well-being
- want more 
    - WHAT FUELS THE CONSTANT DESIRE FOR MORE 
    - how does the mentality affect our perception of success

#### What does a mindless life look like? 
- no daily or regular or incremental improvement
    - why do i consider a lack of growth "mindless"?
    - how to iniate a cycle of constant growth
- not putting yourself in new situation regularly
- caring what others think 
- doing what you think that others' want you to do

#### How does silent observation shape what you become? 
- what is *silent observation* and why is it "important"?
- how can silent observation lead to increased self awareness? 

#### Do you want your time, attention, and life-changing experiences stolen from you?
- no, how can i rectify this? 
    - what are some common ways that people unknowingly get stuff stolen from them 
    - are there strategies to safeguard one's time, attention, and experiences?

#### How can a new definition of *focus*?
- what is the current definition of focus? 
- how might a new or altered definition better server individiual or societal needs? 

#### What is the main metric that determines your everyday quality of life? 
- How do common metrics like income, status, or "success" hold up under scrutiny? 
    - status is important for me, such more so than the other two 
Could *alternatives* like "peace of mind", "emotional well-being", or "meaningful interactions" server as a better indicator?
    - yes i think these are all **neccessary**, but potentially not sufficient. I wonder wghat some other salternative metricds may be? 