---
title: "The Journey of 20,000 steps: How Physical Exercise Keeps You Moving Forward"
format: html
---

Some choices are incredibly high-leverage , such that they serve as such a pivotal moment in your life. *Set the stage for discussing some of your own personal decisions.*

#### Things that have paid off: **shooting your shot**
All of the *meaningful* or the uber beneficial things that I have done between the ages of 18-24 are things that have been meet with slights amount of apprehension or conbcern from those around me. Examples being: 
    - moving out of home to a different city at 18
    - spending six weeks in a rural Chinese village
    - applying to >50 summer internships after third year in a different country
    - continuing with graduate study 
    - moving countries in the middle of a pandemic to begin a PhD
    - **brashly** messaging and communicating with people that 
You got to be in the race, to have a chance of success. No one is going to put themselves out there too much purely on your behalf. You have to lead the way. 

#### Mixed results
Being so future 
*TO BE HONEST, I NEED TO COME UP WITH SOMETHING HERE*
- what were the positive and the negative ramifications 
- explore what these outcomes taught you about yourself and your priorities. 

#### Things that have cost me : **prioritizing monetary gains over** 
Realistically, I am still young, and have no intention of having dependents for another ~15 years. While money and savings and making smart financial decisions are all well and good, lots of the decisions that I have mmade with poor outcomes have been due to prioritizing short-termfinancial gains over interest into situiations that can provide the maximum personal growth. For example, the difference between a place for $50 more per week is potentially night and day in terms of living situation. 

#### The power oof retrospection 
- explain the benefits of regularly reflecting on past choices
- discuss how this practice aids in better decision-making for the future 

#### Looking forward 
At the moment, one of the big *future* choices that I have is that I am moving to Europe in January, and that I have a bunch of big choices to make around this. I have all these decisions that I have to make regarding any thing to do with this move. 

I also have to have the confidence to *let everything work itself out*. This has always been historically difficult for me to do..
- speculate on an upcoming decision and how your past choices and their lessons might influence it 

#### Conclusion 
- wrap up by reiterating that all choices, whether good or bad, serve as stepping stones in the journey of life
- encourage readers to set aside time for their own reflections on past choices to extract valuble life lessons

Look at how fun your life currently is! 
